version: '3.8'

services:
  # PostgreSQL database
  postgres:
    image: postgres:14-alpine
    container_name: openverse-explorer-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-openverse_explorer}
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - app-network

  # Backend API server
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: openverse-explorer-server
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "${SERVER_PORT:-5000}:5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-openverse_explorer}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-your-secret-key}
      OPENVERSE_CLIENT_ID: ${OPENVERSE_CLIENT_ID}
      OPENVERSE_CLIENT_SECRET: ${OPENVERSE_CLIENT_SECRET}
      CORS_ORIGIN: ${CORS_ORIGIN:-http://localhost:3000}
    restart: unless-stopped
    networks:
      - app-network

  # Frontend React application
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: openverse-explorer-client
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    depends_on:
      - server
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL:-http://localhost:5000/api}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: